# Generated by Django 5.2.1 on 2025-06-12 22:56

import tienda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('descrip', models.CharField(max_length=1000)),
                ('precio', models.IntegerField(validators=[tienda.models.validar_precio_minimo])),
                ('es_publico', models.BooleanField(default=True)),
            ],
        ),
    ]
