# Generated by Django 5.2.1 on 2025-06-14 22:51

import django.db.models.deletion
import tienda.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_producto_creado_en_producto_modificado_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('descrip', models.CharField(max_length=1000)),
                ('precio', models.IntegerField(validators=[tienda.models.validar_precio_minimo])),
                ('es_publico', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repuestos_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repuestos_modificados', to=settings.AUTH_USER_MODEL)),
                ('producto_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='tienda.producto')),
            ],
        ),
    ]
