# Generated by Django 5.2.1 on 2025-06-14 23:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_rename_producto_asociado_repuesto_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_mayorista',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
