# Generated by Django 5.2.1 on 2025-06-14 23:47

import tienda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_producto_precio_mayorista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='precio',
            field=models.IntegerField(validators=[tienda.models.validar_precio_rep]),
        ),
    ]
