# Generated by Django 5.2.1 on 2025-06-14 23:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_repuesto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='precio_mayorista',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_mayorista',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(4000000)]),
        ),
    ]
