# Generated by Django 5.2.1 on 2025-06-14 23:55

import tienda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_repuesto_precio_mayorista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_mayorista',
            field=models.IntegerField(default=0, validators=[tienda.models.validar_mayor_pr]),
        ),
    ]
