# Generated by Django 5.2.1 on 2025-06-15 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_categoriaproducto_categoriarepuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='tienda.categoriaproducto'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repuestos', to='tienda.categoriarepuesto'),
        ),
    ]
