# Generated by Django 5.2.1 on 2025-06-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioempresa',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usuarionormal',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
