# Generated by Django 5.2.1 on 2025-06-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0017_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
